services:
  - type: web
    name: shop-inventory-frontend
    rootDir: .
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html